services:
  app:
    container_name: springbootdocker
    image: spring-boot
    restart: unless-stopped
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    container_name: postgresql
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=ayoub
      - POSTGRES_USER=taqi
      - POSTGRES_DB=HomeTeam
    volumes:
      - pg_postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: taqi@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: ayoub
    volumes:
      - pg-admin-postg-data:/var/lib/pgadmin/data

volumes:
  pg_postgres_data:
  pg-admin-postg-data: